# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from db_server_creating import Client, Client_history, Contact_list, Server_DataBase
from sqlalchemy import create_engine
from sqlalchemy.orm import declarative_base

Base = declarative_base()
db_engine = create_engine("sqlite:///server_tables.db", echo=True)
db_prototype = Server_DataBase(engine=db_engine, base=Base)
MAX_WINDOW_LINES = 15


class Ui_MainWindow(object):

    window_lines = 0

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1800, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1800, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1800, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 150, 1771, 621))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_window_text = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Osake")
        font.setPointSize(20)
        self.main_window_text.setFont(font)
        self.main_window_text.setContextMenuPolicy(
            QtCore.Qt.DefaultContextMenu)
        self.main_window_text.setStyleSheet("background-color: rgb(172, 172, 172);\n"
                                            "")
        self.main_window_text.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.main_window_text.setObjectName("main_window_text")
        self.verticalLayout.addWidget(self.main_window_text)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 1771, 131))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Clien_Stat = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Clien_Stat.setMaximumSize(QtCore.QSize(700, 600))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.Clien_Stat.setFont(font)
        self.Clien_Stat.setObjectName("Clien_Stat")
        self.horizontalLayout.addWidget(self.Clien_Stat)
        self.Client_List = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Client_List.setMaximumSize(QtCore.QSize(700, 600))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.Client_List.setFont(font)
        self.Client_List.setObjectName("Client_List")
        self.horizontalLayout.addWidget(self.Client_List)
        self.Button_init = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Button_init.setMaximumSize(QtCore.QSize(700, 600))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.Button_init.setFont(font)
        self.Button_init.setObjectName("Button_init")
        self.horizontalLayout.addWidget(self.Button_init)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Adminka"))
        self.main_window_text.setText(_translate("MainWindow", "text here"))
        self.Clien_Stat.setText(_translate("MainWindow", "Client stat"))
        self.Client_List.setText(_translate("MainWindow", "Client list"))
        self.Button_init.setText(_translate("MainWindow", "init_database"))

    def add_functions(self):
        self.Button_init.clicked.connect(
            lambda: self.initialize_database(db_prototype))

        self.Client_List.clicked.connect(
            lambda: self.show_list_of_clients(db_prototype))

    def initialize_database(self, database_prototype):
        self.write_to_main_text_window(database_prototype.create_db())

    def show_list_of_clients(self, database_prototype):
        self.write_to_main_text_window(database_prototype.show_clients())

    def write_to_main_text_window(self, message):

        if self.window_lines == 0:
            self.main_window_text.setText(f"{message}")
            self.window_lines += 1
        elif self.window_lines == MAX_WINDOW_LINES:
            self.main_window_text.setText(f"{message}")
            self.window_lines = 1
        else:
            self.main_window_text.setText(
                self.main_window_text.text() + f"\n{message}")
            self.window_lines += 1


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    app.exec_()
    # sys.exit()
